### ISSUE TITLE
client: empty metric collected and sent to mongo

### ISSUE THREAD

**Issue by rjeczalik** [jpclark/metrics#3]
Hey @jpclark!

I wanted to send a custom metric to a collector. In order to do that, I've copied `client/payload.json` edited it so it contains my custom, non-empty metric and sent it to the collector with `./client` binary.

Collector logged:

```
2017/05/10 18:38:53 [x] Request received from Go-http-client/1.1
2017/05/10 18:38:53 [x] Sent data to rabbit: {"Username":"","Count":0,"Metric":""}
```

And my RabbitMQ server logged:

```
=INFO REPORT==== 10-May-2017::16:38:53 ===
connection <0.538.0> (172.17.0.1:47654 -> 172.17.0.2:5672): user 'guest' authenticated and granted access to vhost '/'

=INFO REPORT==== 10-May-2017::16:38:53 ===
closing AMQP connection <0.538.0> (172.17.0.1:47654 -> 172.17.0.2:5672)
```

Do you know why the received metric is empty and is forwarded as such to RabbitMQ?

**Comment by jpclark** [comment]
The issue is in the test client, which was written with the assumption that the payload would be valid is it ignores errors instead of quitting when the format is bad. Instead of quitting with an error, the test client sends an empty json request to the collector which dutifully writes the data to rabbit.

There is proper error checking in place on the collector, however. So if a real client sent actual broken data to the collector it will send back an error message. You can test this behavior by editing the client.sh script and sending a broken json request and observing the response.

I'll add an error check to the test client, though. It should have been there to begin with.

**Comment by jpclark** [comment]
bug fix pushed
