### ISSUE TITLE
client: sending XML metrics does not work

### ISSUE THREAD

**Issue by rjeczalik** [jpclark/metrics#4]
Hey @jpclark!

I wanted to send a small piece of XML as a part of Metric field. My payload looks like the following:

```json
{
  "username": "jason",
  "count": 37,
  "metric": "<name>My XML metric</name>"
}
```

When I send it, client sends different metric field than in the payload file, and that metric is received by collector and pushed to RabbitMQ.

Client:

```
2017/05/10 18:43:07 [*] Config: jfile=payload.json, host=localhost, port=8080, loop=1
2017/05/10 18:43:07 [x] Sending data: {"Username":"jason","Count":37,"Metric":"\u003cname\u003eMy XML metric\u003c/name\u003e"}
```

Collector:

```
2017/05/10 18:43:07 [x] Request received from Go-http-client/1.1 
2017/05/10 18:43:07 [x] Sent data to rabbit: {"Username":"jason","Count":37,"Metric":"\u003cname\u003eMy XML metric\u003c/name\u003e"}
```

I'd want to read XML from Metric field from RabbitMQ, but given the above it does not work. Any ideas?

**Comment by jpclark** [comment]
I didn't include any character escaping/unescaping which has led to this problem! The test client sends the angle brackets as unicode escaped characters and the collector simply accepts what it is given, as long as the json itself is formatted correctly.

The quick fix would be to properly encode the data in the test client, but this doesn't fix the real world scenario where other clients could send badly formatted data. 

The good fix would be to always decode/unescape the data on the backend, either in the collector or in the workers. I like the idea of having the workers decode data rather than the collector. The collector should be light weight and do as little processing as possible, but it would take care of the problem in a more centralized way.
